{
 "title": "Linux System Dashboard",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   },
   {
    "name": "GPU",
    "query": "SHOW TAG VALUES FROM \"nvidia_smi\" WITH KEY = \"name\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "cpu_temperature" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "ZFS ARC Hitrate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT\n(max(\"arcstats_hits\") / (max(\"arcstats_misses\") + max(\"arcstats_hits\")) * 100)\nFROM \"zfs\" WHERE $timeFilter AND \"host\" =~ /$server$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "arcstats_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZFS L2ARC Hitrate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT\n(max(\"arcstats_l2_hits\") / (max(\"arcstats_l2_misses\") + max(\"arcstats_l2_hits\")) * 100)\nFROM \"zfs\" WHERE $timeFilter AND \"host\" =~ /$server$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "arcstats_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "S.M.A.R.T", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Smart HD Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "/dev/$tag_device: $tag_model ($tag_serial_no)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(temp_c) as \"Temperature\" FROM \"smart_device\" WHERE \"host\" =~ /$server$/ AND \"device\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), device,model,serial_no fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smart HD Status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT last(\"health_ok\") AS Health, last(temp_c) as \"Temperature\" FROM \"smart_device\" WHERE (\"device\" =~ /^$disk$/) AND $timeFilter GROUP BY \"device\",\"model\" ,\"serial_no\"",
     "select": [
      [
       { "params": [ "health_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "udma_crc_errors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Smart Attributes",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS CommandTimeouts FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Command_Timeout') AND $timeFilter GROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "query": "SELECT last(\"raw_value\") AS CurrentPendingSectors FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Current_Pending_Sector') AND $timeFilter GROUP BY \"device\" fill(null)",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Power_On_Hours" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM\n(SELECT last(\"raw_value\") * 512 * 1024 AS BytesRead FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Data_Units_Read') \nAND $timeFilter \n),\n(SELECT last(\"raw_value\") * 512 AS BytesRead FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Total_LBAs_Read') \nAND $timeFilter \n),\n(SELECT last(\"raw_value\") * 1024 * 1024 * 1024 AS BytesRead FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Host_Reads_GiB') \nAND $timeFilter\n)\nGROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM\n(SELECT last(\"raw_value\") * 512 * 1024 AS BytesWritten FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Data_Units_Written') \nAND $timeFilter \n),\n(SELECT last(\"raw_value\") * 512 AS BytesWritten FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Total_LBAs_Written') \nAND $timeFilter \n),\n(SELECT last(\"raw_value\") * 1024 * 1024 * 1024 AS BytesWritten FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Host_Writes_GiB') \nAND $timeFilter\n)\nGROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS OfflineUncorrectables FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Offline_Uncorrectable') AND $timeFilter GROUP BY \"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS PowerOnHours FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Power_On_Hours') AND $timeFilter GROUP BY \"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS ReallocatedEvents FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Reallocated_Event_Count') AND $timeFilter GROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS ReallocatedSectors FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raw_value\") AS SpinRetrys FROM \"smart_attribute\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$server$/ AND \"name\" = 'Spin_Retry_Count') AND $timeFilter GROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM\n(SELECT 100 - last(\"raw_value\") AS Health FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Percentage_Used') \nAND $timeFilter \n),\n(SELECT 100 - last(\"raw_value\") AS Health FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Media_Wearout_Indicator') \nAND $timeFilter \n),\n(SELECT last(\"value\") AS Health FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Wear_Leveling_Count') \nAND $timeFilter \n),\n(SELECT last(\"value\") AS Health FROM \"smart_attribute\" \nWHERE (\"device\" =~ /^$disk$/ \nAND \"host\" =~ /^$server$/ \nAND \"name\" = 'Percent_Lifetime_Remain') \nAND $timeFilter \n)\nGROUP BY \"device\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/ AND \"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "cpu_temperature" }
     ]
    }
   ]
  },
  {
   "title": "CPU Core Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "CPU Core Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "in_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "cpu_core_voltage" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "System Fans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "$tag_feature",
     "query": "SELECT mean(fan_input) as \"Fan Speed\" FROM \"sensors\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), feature fill(previous)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT non_negative_derivative(mean(\"in\")) as \"in\", non_negative_derivative(mean(\"out\")) as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(\"file-max\") as max FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(\"file-nr\") as opened FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "$server Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server Network Interface Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT\nnon_negative_derivative(max(\"err_in\"), 1s) as \"Errors In\",\nnon_negative_derivative(max(\"drop_in\"), 1s) as \"Dropped In\",\nnon_negative_derivative(max(\"err_out\"), 1s) as \"Errors Out\",\nnon_negative_derivative(max(\"drop_out\"), 1s) as \"Dropped Out\"\nFROM \"net\" WHERE host =~ /$server$/ AND interface !~ /(docker0|veth|br-)/ AND $timeFilter GROUP BY interface, time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server IP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT \nnon_negative_derivative(mean(\"ip_inhdrerrors\"),1s) AS \"IpInHdrErrors\",\nnon_negative_derivative(mean(\"ip_inaddrerrors\"),1s) AS \"IpInAddrErrors\",\nnon_negative_derivative(mean(\"ip_inunknownprotos\"),1s) AS \"IpInUnknownProtos\",\nnon_negative_derivative(mean(\"ip_indiscards\"),1s) AS \"IpInDiscards\",\nnon_negative_derivative(mean(\"ip_outdiscards\"),1s) AS \"IpOutDiscards\",\nnon_negative_derivative(mean(\"ip_outnoroutes\"),1s) AS \"IpOutNoRoutes\",\nnon_negative_derivative(mean(\"ip_reasmtimeout\"),1s) AS \"IpReasmTimeout\",\nnon_negative_derivative(mean(\"ip_reasmfails\"),1s) AS \"IpReasmFails\",\nnon_negative_derivative(mean(\"ip_fragfails\"),1s) AS \"IpFragFails\"\n FROM \"net\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "udp_sndbuferrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$server TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server TCP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT \nnon_negative_derivative(mean(\"tcp_attemptfails\"),1s) AS \"TcpAttemptFails\",\nnon_negative_derivative(mean(\"tcp_estabresets\"),1s) AS \"TcpEstabResets\",\nnon_negative_derivative(mean(\"tcp_incsumerrors\"),1s) AS \"TcpInCsumErrors\",\nnon_negative_derivative(mean(\"tcp_inerrs\"),1s) AS \"TcpInErrs\",\nnon_negative_derivative(mean(\"tcp_outrsts\"),1s) AS \"TcpOutRsts\",\nnon_negative_derivative(mean(\"tcp_retranssegs\"),1s) AS \"TcpRetransSegs\"\n  FROM \"net\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "udp_sndbuferrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$server UDP datagrams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(udp_indatagrams), 1s) as \"UDP datagrams in\" FROM \"net\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(udp_outdatagrams), 1s) as \"UDP datagrams out\" FROM \"net\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(\"udp_sndbuferrors\"),1s) AS \"send buffer errors\", \nnon_negative_derivative(mean(\"udp_rcvbuferrors\"),1s) AS \"recieve buffer errors\", \nnon_negative_derivative(mean(\"udp_incsumerrors\"),1s) AS \"checksum errors\", \nnon_negative_derivative(mean(\"udp_inerrors\"),1s) AS \"in errors\",\nnon_negative_derivative(mean(\"udp_noports\"),1s) AS \"no ports errors\"\n FROM \"net\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "udp_sndbuferrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "$server ZFS ARC Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "ARC $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT mean(\"arcstats_size\") AS \"size\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "arcstats_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ser", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col cache size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT mean(\"arcstats_metadata_size\") AS \"Metadata\", mean(\"arcstats_mfu_size\") AS \"MFU\", mean(\"arcstats_mru_size\") AS \"MRU\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "arcstats_metadata_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Metadata" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mfu_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Frequently Used" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mru_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Reecntly Used" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server ZFS ARC Hitrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "percent", "label": "Hitrate" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT (mean(arcstats_hits) / (mean(arcstats_hits) + mean(arcstats_misses))) * 100 AS \"ARC Hit Rate\" \nFROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    },
    {
     "alias": "$col",
     "query": "SELECT (sum(arcstats_l2_hits) / (sum(arcstats_l2_hits) + sum(arcstats_l2_misses))) * 100 AS \"L2ARC Hit Rate\" \nFROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "$server ZFS ARC Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT non_negative_derivative(mean(\"arcstats_hits\"),1s) AS \"ARC Hits\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "arcstats_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ser", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "query": "SELECT non_negative_derivative(mean(\"arcstats_misses\"),1s) AS \"ARC Misses\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval), * fill(none)"
    }
   ]
  },
  {
   "title": "$server ZFS L2ARC Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "L2ARC $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT mean(\"arcstats_l2_size\") AS \"size\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "arcstats_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ser", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT mean(\"arcstats_l2_hdr_size\") AS \"L2ARC Metadata\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "arcstats_metadata_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Metadata" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mfu_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Frequently Used" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mru_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Reecntly Used" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server ZFS L2ARC I/O bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT \nnon_negative_derivative(mean(arcstats_l2_read_bytes),1s) AS \"L2ARC Read Bytes\",\nnon_negative_derivative(mean(arcstats_l2_write_bytes),1s) AS \"L2ARC Write Bytes\"\n FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "arcstats_metadata_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Metadata" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mfu_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Frequently Used" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_mru_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Most Reecntly Used" ], "type": "alias" }
      ],
      [
       { "params": [ "arcstats_metadata_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Metadata" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server ZFS L2ARC Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT non_negative_derivative(mean(\"arcstats_l2_hits\"),1s) AS \"L2ARC Hits\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "arcstats_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ser", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "query": "SELECT non_negative_derivative(mean(\"arcstats_l2_misses\"),1s) AS \"L2ARC Misses\" FROM \"zfs\" WHERE (\"host\" =~ /$server$/) AND $timeFilter GROUP BY time($interval), * fill(none)"
    }
   ]
  },
  {
   "title": "$server ZFS ARC Evicted L2ARC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "query": "SELECT\nnon_negative_derivative(mean(\"arcstats_evict_l2_eligible\"), 1s) AS evict_l2_eligible,\nnon_negative_derivative(mean(\"arcstats_evict_l2_ineligible\"), 1s) AS evict_l2_ineligible,\nnon_negative_derivative(mean(\"arcstats_evict_l2_cached\"), 1s) AS evict_l2_cached\nFROM \"zfs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "arcstats_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$server ZFS Pool Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT\nmax(\"arcstats_size\") as \"ARC\"\nFROM \"zfs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "nread" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "nwritten" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$server ZFS Zfetch Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "zfetch $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" }
     ],
     "measurement": "zfs",
     "query": "SELECT non_negative_derivative(mean(\"zfetchstats_hits\"), 1s) AS \"hits\", non_negative_derivative(mean(\"zfetchstats_misses\"), 1s) AS \"misses\" FROM \"zfs\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"pool\"",
     "select": [
      [
       { "params": [ "zfetchstats_hits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "hits" ], "type": "alias" }
      ],
      [
       { "params": [ "zfetchstats_misses" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "misses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "$server Storage Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path ($tag_fstype on $tag_device)",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"path\", \"device\", \"fstype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$server Disk I/O Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT\nnon_negative_derivative(mean(read_bytes),1s) as \"read\", non_negative_derivative(mean(write_bytes),1s) as \"write\"\nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND (\"name\" =~ /^sd.$/ OR \"name\" =~ /nvme.n.$/) AND $timeFilter GROUP BY time($__interval), *\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$server Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT\nnon_negative_derivative(mean(reads),1s) AS \"read\", non_negative_derivative(mean(writes),1s) AS \"write\"\nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND (\"name\" =~ /^sd.$/ OR \"name\" =~ /nvme.n.$/) AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$server Disk Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 163 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT\nnon_negative_derivative(mean(read_time), 1s) AS \"Read\",non_negative_derivative(mean(write_time), 1s) AS \"Write\"\nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND (\"name\" =~ /^sd.$/ OR \"name\" =~ /nvme.n.$/) AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "title": "$server Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "$server Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "query": "SELECT mean(\"usage\") FROM \"docker_container_mem\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "$server Container Network Rx/Tx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name Rx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),1s) FROM \"docker_container_net\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "$tag_container_name Tx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),1s) FROM \"docker_container_net\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "$server Container Disk IO Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "query": "SELECT non_negative_derivative(mean(\"io_service_bytes_recursive_read\"),1s) AS \"read\",\nnon_negative_derivative(mean(\"io_service_bytes_recursive_write\"),1s) AS \"write\" \nFROM \"docker_container_blkio\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(null)\n",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_write"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Nvidia GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "repeat": "GPU",
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Memory Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT distinct(\"memory_total\") FROM \"nvidia_smi\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "memory_total" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT distinct(\"memory_used\") FROM \"nvidia_smi\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "memory_used" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
       ]
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "GPU Temperature for  $GPU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT distinct(\"temperature_gpu\") FROM \"nvidia_smi\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temperature_gpu" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage for $cpu",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
     "repeat": "cpu",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $cpu $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 147 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 147 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "pps", "label": "Drops per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "short", "label": "Errors per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}